export const en = {
  contact: "Contact",
  brand: "Our brands",
  about: "Who we are",
  banner_text:
    "Restaurateur? Join the Taster Platform and rapidly launch one of our iconic virtual restaurant brands from your existing kitchen!",
  partner_btn: "Become a partner",
  details_btn: "Learn more",
  best_title: "The best of street food at home",
  landing_desc:
    "Taster is a collection of online restaurants dedicated to bringing the best of street food to you.",
  discover_btn: "Descubre nuestras marcas",
  stats_title: "Bitesize Stats",
  stat1: "4 Years",
  stat2: "425,364 Cheese Slices",
  stat3: "9.2 million Sweet Potato Fries",
  stat4: "7,104 kms of Noodles",
  stat5: "314,530 Tiger Prawns",
  stat6: "1,000,000+ Rides",
  restaurants_count: "100 Restaurants",
  cities_count: "25 Cities",
  brands_count: "5 Brands",
  more_count: "And More!",
  restaurant_title: "Our restaurants",
  restaurant_item1: "Bian Dang",
  restaurant_item2: "A Burgers",
  restaurant_item3: "Mission Saigon",
  restaurant_item4: "Out Fry",
  restaurant_item5: "Stacksando",
  find_title: "Find us",
  find_item1: "Address",
  find_item2: "Sorry, we’re just a digital food court",
  corporate_title: "Corporate",
  corporate_item1: "Contact",
  corporate_item2: "Our Story",
  corporate_item3: "Jobs",
  corporate_item4: "Support",
  social_title: "Socials",
  social_item1: "Instagram",
  social_item2: "Facebook",
  order_title: "Order on",
  order_item1: "Download on Android",
  order_item2: "Download on iOS",
};
