export const es = {
  contact: "Contacto",
  brand: "Nuestras marcas",
  about: "Quienes somos",
  banner_text:
    "¿Restaurador? ¡Únase a Taster Platform y lance rápidamente una de nuestras icónicas marcas de restaurantes virtuales desde su cocina actual!",
  partner_btn: "Convertirse en un compañero",
  details_btn: "Aprende más",
  best_title: "Lo mejor de la comida callejera en casa.",
  landing_desc:
    "Taster es una colección de restaurantes en línea dedicados a ofrecerte lo mejor de la comida callejera.",
  discover_btn: "Découvrez nos marques",
  stats_title: "Estadísticas de tamaño de bocado",
  stat1: "4 Años",
  stat2: "425,364 Lonchas de queso",
  stat3: "9,2 millones Patatas fritas",
  stat4: "7,104 kms de Fideos",
  stat5: "314,530 Gambas tigre",
  stat6: "1,000,000+ Paseos",
  restaurants_count: "100 Restaurantes",
  cities_count: "25 Ciudades",
  brands_count: "5 Marcas",
  more_count: "¡Y más!",
  restaurant_title: "Nuestros restaurantes",
  restaurant_item1: "Bian Dang",
  restaurant_item2: "A Burgers",
  restaurant_item3: "Mission Saigon",
  restaurant_item4: "Out Fry",
  restaurant_item5: "Stacksando",
  find_title: "Encuéntranos",
  find_item1: "Dirección",
  find_item2: "Lo sentimos, solo somos un patio de comidas digital.",
  corporate_title: "Corporativo",
  corporate_item1: "Contacto",
  corporate_item2: "Nuestra historia",
  corporate_item3: "Trabajos",
  corporate_item4: "Apoyo",
  social_title: "Sociales",
  social_item1: "Instagram",
  social_item2: "Facebook",
  order_title: "Orden en",
  order_item1: "Descargar en Android",
  order_item2: "Descargar en iOS",
};
