export const fr = {
  contact: "Contact",
  brand: "Nos marques",
  about: "Qui nous sommes",
  banner_text:
    "Restaurateur? Rejoignez la plateforme Taster et lancez rapidement l'une de nos marques de restaurant virtuel emblématiques depuis votre cuisine existante!",
  partner_btn: "Devenir un partenaire",
  details_btn: "Apprendre encore plus",
  best_title: "Le meilleur de la street food à la maison",
  landing_desc:
    "Taster est une collection de restaurants en ligne dédiés à vous offrir le meilleur de la cuisine de rue.",
  discover_btn: "Découvrez nos marques",
  stats_title: "Statistiques sur la taille des bouchées",
  stat1: "4 <br />Années",
  stat2: "425,364 <br />Tranches de fromage",
  stat3: "9.2 million <br /> Frites de patates <br /> douces",
  stat4: "7,104 kms <br /> de Nouilles",
  stat5: "314,530 <br /> Crevettes tigrées",
  stat6: "1,000,000+ <br /> Manèges",
  restaurants_count: "100 Restaurants",
  cities_count: "25 Villes",
  brands_count: "5 Marques",
  more_count: "Et plus!",
  restaurant_title: "Nos restaurants",
  restaurant_item1: "Bian Dang",
  restaurant_item2: "A Burgers",
  restaurant_item3: "Mission Saigon",
  restaurant_item4: "Out Fry",
  restaurant_item5: "Stacksando",
  find_title: "Trouve nous",
  find_item1: "Adresse",
  find_item2: "Désolé, nous ne sommes qu'une aire de restauration numérique",
  corporate_title: "Entreprise",
  corporate_item1: "Contact",
  corporate_item2: "Notre histoire",
  corporate_item3: "Emplois",
  corporate_item4: "Soutien",
  social_title: "Réseaux sociaux",
  social_item1: "Instagram",
  social_item2: "Facebook",
  order_title: "Commandez sur",
  order_item1: "Télécharger sur Android",
  order_item2: "Télécharger sur iOS",
};
